deploy:
  provider: heroku
  api_key:
    secure: Ygw/j3xjLLjMt7eNQtzmwhL4WqEHzo1wG0swzTsmVRYGuiYwDrpmfSvulggvz6diDff8kW3f5cUZ0QUgg5ZL4J9TTnHJx8XLO65pF+Zy+H2nU0Ma/wIjf0N4y9KYOOGQQmXtOXbCkoDWTTiDtLQRFKOoMK7h0elGDYnUUfIq3/oispG2NpWFbzsj3lPqr+20V4GjTa2pCRPOasVvMvrdASa54qcGBkoAg5l4tlzBsgfYjeTbF59WBeEgXHPaWvz2G5LZvwEAIpKEsA/djHN/jZl8Ts5KFG31TvCAfdJR+RXiNzxMk8jQqtNjyoe7AFni9W3pCKnLZSyKm3PCm8gMxdQ1zRostAeoa0TA1ogfwazpY9eh5PTdSdRXwOegMCpjmhTAPYrfcbFZ8cCZRy7j5KLrfLmVsg4nMZBT5yPAwT1HrWobBQi1Xu2x5KbcQbSkSHEtDHafG58JNDoagJmgiyV45wJmUrWXeaoBnfqGUlHbiyjyQjikaC+FHyembfHhl/Av9UgKSl793U2GIPpRbJk47iQw0stShy9kcDmlURICzZBkopkMwZ3z0S1deMFIFagkbQRX9W8PRVX/6/23AYUPRL/K+Kl21HB16KvDIpAKSnra6fSLxIkXNHsxNKcbVFqcWiqGcD1F/SSSl6x4luEyIFMpsZVtHV7e+rrpMas=
  app: thawing-headland-78405
  on:
    repo: JustInToCoding/phoenix_todo
